/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/OkCancelDialog.java to edit this template
 */
package com.mycompany.chick_int_dtr_system.Components;



import com.mycompany.chick_int_dtr_system.Dashboard;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;



/**
 *
 * @author Ronald
 */
public class AddEmployeeModal extends javax.swing.JDialog {

    private Dashboard dashboard;
    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form AddEmployeeModal
     */
    public AddEmployeeModal(com.mycompany.chick_int_dtr_system.Dashboard parent, boolean modal) {
        super(parent, modal);
        dashboard = parent;
        initComponents();
        
        
        
        
        
        

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        main = new javax.swing.JPanel();
        jForm = new javax.swing.JPanel();
        FNameMain = new javax.swing.JPanel();
        FName = new javax.swing.JPanel();
        jFirstName = new javax.swing.JTextField();
        lFirstName = new javax.swing.JLabel();
        jMiddleName = new javax.swing.JTextField();
        lMiddleName = new javax.swing.JLabel();
        jLastName = new javax.swing.JTextField();
        lLastName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        FGenderAgeBirthMain = new javax.swing.JPanel();
        jGender = new javax.swing.JTextField();
        lGender = new javax.swing.JLabel();
        jAge = new javax.swing.JTextField();
        lAge = new javax.swing.JLabel();
        jBirth = new javax.swing.JTextField();
        lBirth = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        FAddressMain = new javax.swing.JPanel();
        FAddess = new javax.swing.JPanel();
        jStreetAddress = new javax.swing.JTextField();
        lStreet = new javax.swing.JLabel();
        jCity = new javax.swing.JTextField();
        lCity = new javax.swing.JLabel();
        jRegion = new javax.swing.JTextField();
        lRegion = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPostalCode = new javax.swing.JTextField();
        lPostalCode = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        FContactMain = new javax.swing.JPanel();
        FContact = new javax.swing.JPanel();
        jPhoneNumber = new javax.swing.JTextField();
        lPhoneNumber = new javax.swing.JLabel();
        jEmail = new javax.swing.JTextField();
        lEmail = new javax.swing.JLabel();
        jEmergencyName = new javax.swing.JTextField();
        lEmergencyName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jEmergencyNumber = new javax.swing.JTextField();
        lEmergencyNumber = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        FPositionMain = new javax.swing.JPanel();
        FPosition = new javax.swing.JPanel();
        jPhoneNumber1 = new javax.swing.JTextField();
        lPhoneNumber1 = new javax.swing.JLabel();
        jEmail1 = new javax.swing.JTextField();
        lEmail1 = new javax.swing.JLabel();
        jEmergencyName1 = new javax.swing.JTextField();
        lEmergencyName1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jEmergencyNumber1 = new javax.swing.JTextField();
        lEmergencyNumber1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 700));
        setPreferredSize(new java.awt.Dimension(600, 700));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(500, 500));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 500));

        jPanel1.setLayout(new java.awt.BorderLayout());

        buttonPanel.setBackground(new java.awt.Color(255, 206, 0));
        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(okButton);
        getRootPane().setDefaultButton(okButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(cancelButton);

        jPanel1.add(buttonPanel, java.awt.BorderLayout.PAGE_END);

        main.setBackground(new java.awt.Color(255, 206, 0));
        main.setLayout(new java.awt.BorderLayout());

        jForm.setBackground(new java.awt.Color(255, 206, 0));
        jForm.setPreferredSize(new java.awt.Dimension(500, 450));
        jForm.setRequestFocusEnabled(false);

        FNameMain.setMinimumSize(new java.awt.Dimension(100, 100));
        FNameMain.setPreferredSize(new java.awt.Dimension(600, 100));
        FNameMain.setLayout(new java.awt.BorderLayout());

        FName.setBackground(new java.awt.Color(255, 206, 0));
        java.awt.GridBagLayout FNameLayout = new java.awt.GridBagLayout();
        FNameLayout.columnWidths = new int[] {0, 13, 0, 13, 0, 13, 0, 13, 0, 13, 0};
        FNameLayout.rowHeights = new int[] {0, 1, 0, 1, 0, 1, 0};
        FName.setLayout(FNameLayout);

        jFirstName.setColumns(12);
        jFirstName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jFirstName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jFirstName.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jFirstName.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jFirstName.setMinimumSize(new java.awt.Dimension(5, 32));
        jFirstName.setOpaque(true);
        jFirstName.setPreferredSize(new java.awt.Dimension(160, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        FName.add(jFirstName, gridBagConstraints);

        lFirstName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lFirstName.setText("First Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        FName.add(lFirstName, gridBagConstraints);

        jMiddleName.setColumns(12);
        jMiddleName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMiddleName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMiddleName.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jMiddleName.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jMiddleName.setMinimumSize(new java.awt.Dimension(5, 32));
        jMiddleName.setOpaque(true);
        jMiddleName.setPreferredSize(new java.awt.Dimension(160, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        FName.add(jMiddleName, gridBagConstraints);

        lMiddleName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lMiddleName.setText("Middle Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        FName.add(lMiddleName, gridBagConstraints);

        jLastName.setColumns(12);
        jLastName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLastName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLastName.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jLastName.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jLastName.setMinimumSize(new java.awt.Dimension(5, 32));
        jLastName.setOpaque(true);
        jLastName.setPreferredSize(new java.awt.Dimension(160, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 6;
        FName.add(jLastName, gridBagConstraints);

        lLastName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lLastName.setText("Last Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        FName.add(lLastName, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Personal Information:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        FName.add(jLabel1, gridBagConstraints);

        FNameMain.add(FName, java.awt.BorderLayout.CENTER);

        jForm.add(FNameMain);

        FGenderAgeBirthMain.setBackground(new java.awt.Color(255, 206, 0));
        FGenderAgeBirthMain.setMinimumSize(new java.awt.Dimension(600, 100));
        FGenderAgeBirthMain.setPreferredSize(new java.awt.Dimension(600, 100));
        java.awt.GridBagLayout FGenderAgeBirthLayout = new java.awt.GridBagLayout();
        FGenderAgeBirthLayout.columnWidths = new int[] {0, 13, 0, 13, 0, 13, 0, 13, 0, 13, 0};
        FGenderAgeBirthLayout.rowHeights = new int[] {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
        FGenderAgeBirthMain.setLayout(FGenderAgeBirthLayout);

        jGender.setColumns(12);
        jGender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jGender.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jGender.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jGender.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jGender.setMinimumSize(new java.awt.Dimension(5, 32));
        jGender.setOpaque(true);
        jGender.setPreferredSize(new java.awt.Dimension(160, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        FGenderAgeBirthMain.add(jGender, gridBagConstraints);

        lGender.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lGender.setText("Gender");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        FGenderAgeBirthMain.add(lGender, gridBagConstraints);

        jAge.setColumns(12);
        jAge.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jAge.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jAge.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jAge.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jAge.setMinimumSize(new java.awt.Dimension(5, 32));
        jAge.setOpaque(true);
        jAge.setPreferredSize(new java.awt.Dimension(160, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        FGenderAgeBirthMain.add(jAge, gridBagConstraints);

        lAge.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lAge.setText("Age");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        FGenderAgeBirthMain.add(lAge, gridBagConstraints);

        jBirth.setColumns(12);
        jBirth.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBirth.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jBirth.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jBirth.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jBirth.setMinimumSize(new java.awt.Dimension(5, 32));
        jBirth.setOpaque(true);
        jBirth.setPreferredSize(new java.awt.Dimension(160, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        FGenderAgeBirthMain.add(jBirth, gridBagConstraints);

        lBirth.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lBirth.setText("Birth Date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        FGenderAgeBirthMain.add(lBirth, gridBagConstraints);

        jForm.add(FGenderAgeBirthMain);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setMinimumSize(new java.awt.Dimension(500, 10));
        jSeparator1.setPreferredSize(new java.awt.Dimension(500, 10));
        jForm.add(jSeparator1);

        FAddressMain.setMinimumSize(new java.awt.Dimension(600, 150));
        FAddressMain.setPreferredSize(new java.awt.Dimension(600, 150));
        FAddressMain.setLayout(new java.awt.BorderLayout());

        FAddess.setBackground(new java.awt.Color(255, 206, 0));
        FAddess.setMinimumSize(new java.awt.Dimension(296, 300));
        FAddess.setPreferredSize(new java.awt.Dimension(296, 300));
        java.awt.GridBagLayout FName1Layout = new java.awt.GridBagLayout();
        FName1Layout.columnWidths = new int[] {0, 5, 0, 5, 0};
        FName1Layout.rowHeights = new int[] {0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0};
        FAddess.setLayout(FName1Layout);

        jStreetAddress.setColumns(20);
        jStreetAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jStreetAddress.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jStreetAddress.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jStreetAddress.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jStreetAddress.setMinimumSize(new java.awt.Dimension(160, 32));
        jStreetAddress.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        FAddess.add(jStreetAddress, gridBagConstraints);

        lStreet.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lStreet.setText("Street Address");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        FAddess.add(lStreet, gridBagConstraints);

        jCity.setColumns(20);
        jCity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCity.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jCity.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jCity.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jCity.setMinimumSize(new java.awt.Dimension(160, 32));
        jCity.setOpaque(true);
        jCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCityActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        FAddess.add(jCity, gridBagConstraints);

        lCity.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lCity.setText("City");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        FAddess.add(lCity, gridBagConstraints);

        jRegion.setColumns(20);
        jRegion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRegion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jRegion.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jRegion.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jRegion.setMinimumSize(new java.awt.Dimension(160, 32));
        jRegion.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        FAddess.add(jRegion, gridBagConstraints);

        lRegion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lRegion.setText("Region");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        FAddess.add(lRegion, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Address:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        FAddess.add(jLabel3, gridBagConstraints);

        jPostalCode.setColumns(20);
        jPostalCode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPostalCode.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPostalCode.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPostalCode.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jPostalCode.setMinimumSize(new java.awt.Dimension(160, 32));
        jPostalCode.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        FAddess.add(jPostalCode, gridBagConstraints);

        lPostalCode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lPostalCode.setText("Postal Code");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        FAddess.add(lPostalCode, gridBagConstraints);

        FAddressMain.add(FAddess, java.awt.BorderLayout.CENTER);

        jForm.add(FAddressMain);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setMinimumSize(new java.awt.Dimension(500, 10));
        jSeparator2.setPreferredSize(new java.awt.Dimension(500, 10));
        jForm.add(jSeparator2);

        FContactMain.setMinimumSize(new java.awt.Dimension(600, 150));
        FContactMain.setPreferredSize(new java.awt.Dimension(600, 150));
        FContactMain.setLayout(new java.awt.BorderLayout());

        FContact.setBackground(new java.awt.Color(255, 206, 0));
        FContact.setMinimumSize(new java.awt.Dimension(296, 300));
        FContact.setPreferredSize(new java.awt.Dimension(296, 300));
        java.awt.GridBagLayout FAddess1Layout = new java.awt.GridBagLayout();
        FAddess1Layout.columnWidths = new int[] {0, 5, 0, 5, 0};
        FAddess1Layout.rowHeights = new int[] {0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0};
        FContact.setLayout(FAddess1Layout);

        jPhoneNumber.setColumns(20);
        jPhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPhoneNumber.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPhoneNumber.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPhoneNumber.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jPhoneNumber.setMinimumSize(new java.awt.Dimension(160, 32));
        jPhoneNumber.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        FContact.add(jPhoneNumber, gridBagConstraints);

        lPhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lPhoneNumber.setText("Phone Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        FContact.add(lPhoneNumber, gridBagConstraints);

        jEmail.setColumns(20);
        jEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jEmail.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jEmail.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jEmail.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jEmail.setMinimumSize(new java.awt.Dimension(160, 32));
        jEmail.setOpaque(true);
        jEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmailActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        FContact.add(jEmail, gridBagConstraints);

        lEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lEmail.setText("E-mail");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        FContact.add(lEmail, gridBagConstraints);

        jEmergencyName.setColumns(20);
        jEmergencyName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jEmergencyName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jEmergencyName.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jEmergencyName.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jEmergencyName.setMinimumSize(new java.awt.Dimension(160, 32));
        jEmergencyName.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        FContact.add(jEmergencyName, gridBagConstraints);

        lEmergencyName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lEmergencyName.setText("Emergency Contact Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        FContact.add(lEmergencyName, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Contact:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        FContact.add(jLabel4, gridBagConstraints);

        jEmergencyNumber.setColumns(20);
        jEmergencyNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jEmergencyNumber.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jEmergencyNumber.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jEmergencyNumber.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jEmergencyNumber.setMinimumSize(new java.awt.Dimension(160, 32));
        jEmergencyNumber.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        FContact.add(jEmergencyNumber, gridBagConstraints);

        lEmergencyNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lEmergencyNumber.setText("Emergency Contact  Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        FContact.add(lEmergencyNumber, gridBagConstraints);

        FContactMain.add(FContact, java.awt.BorderLayout.CENTER);

        jForm.add(FContactMain);

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setMinimumSize(new java.awt.Dimension(500, 10));
        jSeparator3.setPreferredSize(new java.awt.Dimension(500, 10));
        jForm.add(jSeparator3);

        FPositionMain.setMinimumSize(new java.awt.Dimension(600, 150));
        FPositionMain.setPreferredSize(new java.awt.Dimension(600, 150));
        FPositionMain.setLayout(new java.awt.BorderLayout());

        FPosition.setBackground(new java.awt.Color(255, 206, 0));
        FPosition.setMinimumSize(new java.awt.Dimension(296, 300));
        FPosition.setPreferredSize(new java.awt.Dimension(296, 300));
        FPosition.setLayout(new java.awt.GridBagLayout());

        jPhoneNumber1.setColumns(20);
        jPhoneNumber1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPhoneNumber1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPhoneNumber1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPhoneNumber1.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jPhoneNumber1.setMinimumSize(new java.awt.Dimension(160, 32));
        jPhoneNumber1.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        FPosition.add(jPhoneNumber1, gridBagConstraints);

        lPhoneNumber1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lPhoneNumber1.setText("Phone Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        FPosition.add(lPhoneNumber1, gridBagConstraints);

        jEmail1.setColumns(20);
        jEmail1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jEmail1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jEmail1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jEmail1.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jEmail1.setMinimumSize(new java.awt.Dimension(160, 32));
        jEmail1.setOpaque(true);
        jEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmail1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        FPosition.add(jEmail1, gridBagConstraints);

        lEmail1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lEmail1.setText("E-mail");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        FPosition.add(lEmail1, gridBagConstraints);

        jEmergencyName1.setColumns(20);
        jEmergencyName1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jEmergencyName1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jEmergencyName1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jEmergencyName1.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jEmergencyName1.setMinimumSize(new java.awt.Dimension(160, 32));
        jEmergencyName1.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        FPosition.add(jEmergencyName1, gridBagConstraints);

        lEmergencyName1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lEmergencyName1.setText("Emergency Contact Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        FPosition.add(lEmergencyName1, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Position Information");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        FPosition.add(jLabel5, gridBagConstraints);

        jEmergencyNumber1.setColumns(20);
        jEmergencyNumber1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jEmergencyNumber1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jEmergencyNumber1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jEmergencyNumber1.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jEmergencyNumber1.setMinimumSize(new java.awt.Dimension(160, 32));
        jEmergencyNumber1.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        FPosition.add(jEmergencyNumber1, gridBagConstraints);

        lEmergencyNumber1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lEmergencyNumber1.setText("Emergency Contact  Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        FPosition.add(lEmergencyNumber1, gridBagConstraints);

        FPositionMain.add(FPosition, java.awt.BorderLayout.CENTER);

        jForm.add(FPositionMain);

        main.add(jForm, java.awt.BorderLayout.CENTER);

        jPanel1.add(main, java.awt.BorderLayout.CENTER);

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(255, 206, 0));
        jPanel3.setMinimumSize(new java.awt.Dimension(251, 60));
        jPanel3.setPreferredSize(new java.awt.Dimension(586, 60));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel2.setBackground(new java.awt.Color(248, 98, 24));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(248, 98, 24));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("New Employee");
        jPanel3.add(jLabel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void jCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCityActionPerformed

    private void jEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmailActionPerformed

    private void jEmail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmail1ActionPerformed
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddEmployeeModal dialog = new AddEmployeeModal(new com.mycompany.chick_int_dtr_system.Dashboard(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FAddess;
    private javax.swing.JPanel FAddressMain;
    private javax.swing.JPanel FContact;
    private javax.swing.JPanel FContactMain;
    private javax.swing.JPanel FGenderAgeBirthMain;
    private javax.swing.JPanel FName;
    private javax.swing.JPanel FNameMain;
    private javax.swing.JPanel FPosition;
    private javax.swing.JPanel FPositionMain;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField jAge;
    private javax.swing.JTextField jBirth;
    private javax.swing.JTextField jCity;
    private javax.swing.JTextField jEmail;
    private javax.swing.JTextField jEmail1;
    private javax.swing.JTextField jEmergencyName;
    private javax.swing.JTextField jEmergencyName1;
    private javax.swing.JTextField jEmergencyNumber;
    private javax.swing.JTextField jEmergencyNumber1;
    private javax.swing.JTextField jFirstName;
    private javax.swing.JPanel jForm;
    private javax.swing.JTextField jGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jLastName;
    private javax.swing.JTextField jMiddleName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jPhoneNumber;
    private javax.swing.JTextField jPhoneNumber1;
    private javax.swing.JTextField jPostalCode;
    private javax.swing.JTextField jRegion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jStreetAddress;
    private javax.swing.JLabel lAge;
    private javax.swing.JLabel lBirth;
    private javax.swing.JLabel lCity;
    private javax.swing.JLabel lEmail;
    private javax.swing.JLabel lEmail1;
    private javax.swing.JLabel lEmergencyName;
    private javax.swing.JLabel lEmergencyName1;
    private javax.swing.JLabel lEmergencyNumber;
    private javax.swing.JLabel lEmergencyNumber1;
    private javax.swing.JLabel lFirstName;
    private javax.swing.JLabel lGender;
    private javax.swing.JLabel lLastName;
    private javax.swing.JLabel lMiddleName;
    private javax.swing.JLabel lPhoneNumber;
    private javax.swing.JLabel lPhoneNumber1;
    private javax.swing.JLabel lPostalCode;
    private javax.swing.JLabel lRegion;
    private javax.swing.JLabel lStreet;
    private javax.swing.JPanel main;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
